config/routes.rb
Rails.application.routes.draw do

  root 'books#HomePage'

  get 'books/HomePage'
  get 'books/AddBook'
  #get 'books/UpdateBook'
  #get 'books/Details'
  #get 'books/Delete'
  get 'demo/index'
  get 'demo/hello'
  resources :books do
    member do
      get :Details
      get :AddBook
      get :UpdateBook
      get :Delete
      get :update
    end
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def HomePage
    @books = Book.all
  end

  def AddBook
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)

    if @book.save
      flash[:notice] = "Book created successfully!"
      redirect_to({:controller => 'books', :action => 'HomePage'}) #need this because we're not redirecting to index, but HomePage (need to figure out how to change default index to HomePage)
    else
      render('AddBook')
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update_attributes(book_params)
      flash[:notice] = "Book updated successfully!"
      redirect_to({:controller => 'books', :action => 'HomePage'}) #need this because we're not redirecting to index, but HomePage (need to figure out how to change default index to HomePage)
    else
      render('UpdateBook')
    end
  end

  def UpdateBook
    @book = Book.find(params[:id])
  end

  def Details
    @book = Book.find(params[:id])
  end

  def Delete
    @book = Book.find(params[:id])
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    flash[:notice] = "'#{@book.title}' destroyed successfully!"
    redirect_to({:controller => 'books', :action => 'HomePage'})
  end

  def book_params
    params.require(:book).permit(:title, :author, :genre, :price, :'published_date')
  end
end

app/controllers/demo_controller.rb
class DemoController < ApplicationController

  layout false
  def index
  end

  def hello
    @array = [1,2,3,4,5]
    @id = params['id']
    @page = params[:page]
  end

  def AddBook
  end

  def DeletePage
  end

  def HomePage
  end

  def ShowDetails
  end

  def UpdateBook
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/demo_helper.rb
module DemoHelper
end

app/views/books/AddBook.html.erb
<%= link_to("<< Back to List", {:controller => 'books', :action => 'HomePage'}, :class => 'back-link') %>

<div class="books new">
  <h2>Create book</h2>

  <%= form_for(@book, :url => books_path, :method => 'post') do |f| %>

    <table summary="book form fields">
      <tr>
        <th>Title</th>
        <td><%= f.text_field(:title) %></td>
      </tr>
      <tr>
        <th>Author</th>
        <td><%= f.text_field(:author) %></td>
      </tr>
      <tr>
        <th>Genre</th>
        <td><%= f.select(:genre, ['mystery','romance','action','adventure','fantasy','sci fi','nonfiction'])%></td>
      </tr>
       <tr>
        <th>Price</th>
        <td><%= f.text_field(:price) %></td>
      </tr>
      <tr>
        <th>Date Published</th>
        <td><%= f.datetime_select(:'published_date', :start_year => 1450, :order => [:day, :month, :year], :discard_hour => true) %></td>
      </tr>
    </table>

    <div class="form-buttons">
      <%= f.submit("Create book") %>
    </div>

  <% end %>
</div>

app/views/books/Delete.html.erb
<%= link_to("<< Back to List", {:controller => 'books', :action => 'HomePage'}, :class => 'back-link') %>

<div class="books delete">
  <h2>Delete book</h2>

  <%= form_for(@book, :method => 'delete') do |f| %>

    <p>Are you sure you want to permanently delete this book?</p>

    <p class="reference-name"><%= f.object.title %></p>

    <div class="form-buttons">
      <%= f.submit("Delete book") %>
    </div>

  <% end %>
</div>

app/views/books/Details.html.erb
<%= link_to("<< Back to List", {:controller => 'books', :action => 'HomePage'}, :class => 'back-link') %>

<div class="books show">
  <h2>Show book</h2>

  <table summary="book detail view">
    <tr>
      <th>Name</th>
      <td><%= @book.title %></td>
    </tr>
    <tr>
      <th>Author</th>
      <td><%= @book.author %></td>
    </tr>
    <tr>
      <th>Genre</th>
      <td><%= @book.genre %></td>
    </tr>
    <tr>
      <th>Price</th>
      <td><%= @book.price %></td>
    </tr>
    <tr>
      <th>Date Published</th>
      <td><%= @book.published_date %></td>
    </tr>
    <tr>
      <th>Entry Created</th>
      <td><%= @book.created_at %></td>
    </tr>
    <tr>
      <th>Entry Updated</th>
      <td><%= @book.updated_at %></td>
    </tr>
  </table>

</div>

app/views/books/HomePage.html.erb
<%if !flash[:notice].blank?%>
  <div class ="notice">
    <%= flash[:notice] %>
  </div>
<%end%>

<div class="books index">
  <h2>books</h2>

  <%= link_to("Add New book", {:controller => 'books', :action => 'AddBook'}, :class => 'action new') %>

  <table class="listing" summary="book list">
    <tr class="header">
      <th>Title</th>
      <th>Author</th>
      <th>Genre</th>
      <th>Price</th>
      <th>Date Published</th>
    </tr>
    <% @books.each do |book| %>
    <tr>
      <td><%= book.title %></td>
      <td><%= book.author %></td>
      <td><%= book.genre %></td>
      <td><%= book.price %></td>
      <td><%= book.published_date %></td>
      <td class="actions">
        <%= link_to("Show Details", {:controller => 'books', :action => 'Details', :id => book.id}, :class => 'action show') %>
        <%= link_to("Update", {:controller => 'books', :action => 'UpdateBook', :id => book.id}, :class => 'action edit') %>
        <%= link_to("Delete", {:controller => 'books', :action => 'Delete', :id => book.id}, :class => 'action delete') %>
      </td>
    </tr>
    <% end %>
  </table>
</div>

app/views/books/UpdateBook.html.erb
<%= link_to("<< Back to List", {:controller => 'books', :action => 'HomePage'}, :class => 'back-link') %>

<div class="books update">
  <h2>Update book</h2>

  <%= form_for(@book) do |f| %>

    <table summary="book form fields">
      <tr>
        <th>Title</th>
        <td><%= f.text_field(:title) %></td>
      </tr>
      <tr>
        <th>Author</th>
        <td><%= f.text_field(:author) %></td>
      </tr>
      <tr>
        <th>Genre</th>
        <td><%= f.select(:genre, ['mystery','romance','action','adventure','fantasy','sci fi','nonfiction'])%></td>
      </tr>
       <tr>
        <th>Price</th>
        <td><%= f.text_field(:price) %></td>
      </tr>
      <tr>
        <th>Date Published</th>
        <td><%= f.datetime_select(:'published_date', :start_year => 1450, :order => [:day, :month, :year], :discard_hour => true) %></td>
      </tr>
    </table>

    <div class="form-buttons">
      <%= f.submit("Update book") %>
    </div>

  <% end %>
</div>

app/views/demo/hello.html.erb
<h1>Hello world from Hello!</h1>

<% @array.each do |n| %>
    <%= n %> </br>
<% end %>

<%= link_to('its a link!', {:action => 'hello'})%> </br>

ID: <%= @id %> </br>
ID: <%= params[:id] %> </br>
Page : <%= @page %> </br>

app/views/demo/index.html.erb
<h1>Hello world from Index!</h1>

<%= link_to('its a link with parameters!', {:action => 'hello', :page => 5, :id => 20})%> </br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BooksLab</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>